# Generated by Django 5.1.3 on 2024-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cryptocurrency_daily_high_cryptocurrency_daily_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_1h_ago',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_24h_ago',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=30),
        ),
    ]
